# Generated by Django 2.2.5 on 2020-02-12 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classificationimage',
            name='content',
        ),
        migrations.RemoveField(
            model_name='classificationimage',
            name='title',
        ),
    ]
